# Generated by Django 4.2.7 on 2023-12-28 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                ("contact_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "email_from",
                    models.EmailField(max_length=254, verbose_name="Email from"),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Subject")),
                ("message", models.TextField(max_length=2048, verbose_name="Message")),
            ],
            options={
                "verbose_name": "Contact Us",
                "verbose_name_plural": "Contact Us",
            },
        ),
        migrations.CreateModel(
            name="RequestResponseTimeMiddlewareModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("request_method", models.CharField(max_length=20)),
                ("execute_time", models.DecimalField(decimal_places=4, max_digits=5)),
            ],
            options={
                "verbose_name": "Log",
                "verbose_name_plural": "Logs",
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_url",
                    models.CharField(max_length=255, verbose_name="Source URL"),
                ),
                (
                    "source_name",
                    models.CharField(max_length=64, verbose_name="Source name"),
                ),
            ],
            options={
                "verbose_name": "Source",
                "verbose_name_plural": "Sources",
            },
        ),
        migrations.CreateModel(
            name="Rate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "buy",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Buy"
                    ),
                ),
                (
                    "sell",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Sell"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "currency_type",
                    models.SmallIntegerField(
                        choices=[(1, "USD"), (2, "EUR")],
                        default=1,
                        verbose_name="Currency type",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="currency.source",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rate",
                "verbose_name_plural": "Rates",
            },
        ),
    ]
