# Generated by Django 4.2.7 on 2023-12-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0003_source_alter_rate_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="source_url",
            field=models.CharField(max_length=255),
        ),
    ]
