# Generated by Django 4.2.7 on 2023-12-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0004_alter_source_source_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rate",
            name="currency_type",
            field=models.CharField(
                choices=[("USD", "Dollar"), ("EUR", "Euro")], max_length=3
            ),
        ),
    ]
