# Generated by Django 4.2.7 on 2023-12-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0005_alter_rate_currency_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactus",
            name="message",
            field=models.TextField(max_length=2048),
        ),
    ]
