# Generated by Django 4.2.7 on 2023-12-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0007_alter_rate_currency_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestResponseTimeMiddlewareModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("request_method", models.CharField(max_length=20)),
                ("execute_time", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterModelOptions(
            name="contactus",
            options={"verbose_name": "Contact Us", "verbose_name_plural": "Contact Us"},
        ),
        migrations.AlterModelOptions(
            name="rate",
            options={"verbose_name": "Rate", "verbose_name_plural": "Rates"},
        ),
        migrations.AlterModelOptions(
            name="source",
            options={"verbose_name": "Source", "verbose_name_plural": "Sources"},
        ),
        migrations.AlterField(
            model_name="contactus",
            name="email_from",
            field=models.EmailField(max_length=254, verbose_name="Email from"),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="message",
            field=models.TextField(max_length=2048, verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="subject",
            field=models.CharField(max_length=255, verbose_name="Subject"),
        ),
        migrations.AlterField(
            model_name="rate",
            name="buy",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Buy"
            ),
        ),
        migrations.AlterField(
            model_name="rate",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="rate",
            name="currency_type",
            field=models.SmallIntegerField(
                choices=[(1, "USD"), (2, "EUR")],
                default=1,
                verbose_name="Currency type",
            ),
        ),
        migrations.AlterField(
            model_name="rate",
            name="sell",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Sell"
            ),
        ),
        migrations.AlterField(
            model_name="rate",
            name="source",
            field=models.CharField(max_length=255, verbose_name="Source"),
        ),
        migrations.AlterField(
            model_name="source",
            name="source_name",
            field=models.CharField(max_length=64, verbose_name="Source name"),
        ),
        migrations.AlterField(
            model_name="source",
            name="source_url",
            field=models.CharField(max_length=255, verbose_name="Source URL"),
        ),
    ]
