# Generated by Django 4.2.7 on 2023-12-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0008_requestresponsetimemiddlewaremodel_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="requestresponsetimemiddlewaremodel",
            options={"verbose_name": "Log", "verbose_name_plural": "Logs"},
        ),
        migrations.AlterField(
            model_name="requestresponsetimemiddlewaremodel",
            name="execute_time",
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
    ]
