# Generated by Django 4.2.7 on 2024-01-15 13:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
