# Generated by Django 4.2.7 on 2024-01-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, default=None, max_length=20, null=True, verbose_name="Phone"
            ),
        ),
    ]
